### ISSUE TITLE
GSB dataset access

### ISSUE THREAD

**Issue by anyuzoey** [augustoicaro/SFD-CNN-TL#1]
Hi @augustoicaro 

I'm researching on this topic as well. I just read your paper, the way you process your data looks very interesting. I was also suspicious that the frequency may be one of the reason. 
I was wondering do you have the original sgy file of the GSB dataset. Can I access that? I want to export directly from the sgy file to make sure I have the best resolution I can get. 
Looking forward to your reply and thank you for your work.

**Comment by augustoicaro** [comment]
Hello @anyuzoey,

Thanks for reading my paper and your contact. Yes, you can access the GSB original segy, it is an open data of the [New Zeland government](https://data.nzpam.govt.nz/GOLD/system/mainframe.asp). You need to "order" Great South Basin final full stack data and then Mr. Hamish Cameron will contact you with further information about your download. This segy is a 40gb data, but as Mr. Haibin Di did in his paper we used a subvolume of the original data at inline 1565 to 2531 with step 2, crossline 2568 to 3568 with step 2, and time -1000 ms to -1400 ms with step -4 ms, as described in my paper.

**Comment by augustoicaro** [comment]
Hello @anyuzoey,

If you send me an email, I can send you the email of Mr. Hamish Cameron so that you can ask for the data directly, and he can help you with all this process.
