### ISSUE TITLE
test data missing/inconsistent with paper

### ISSUE THREAD

**Issue by anyuzoey** [augustoicaro/SFD-CNN-TL#2]
Hi @augustoicaro 
I was trying to reproduce your work, and I found that for 5 GSB test example shown in your paper, you only provide 3 mask file (crl2800, inl1796 and inl2011) in this repo.  I'm wondering if you could upload the other two crosslines mask file (crl2600 and crl3000)? 
Other than the missing mask file. I also found that inl1796.csv is the shape of (498,76) size which is inconsistent with the crossline range (2568,3568 with a step size of 2) and also inconsistent with the inl2011.csv shape (501,76). Could you please help me confirm this?  
I tried to reproduce the mask based on your demo in TrainAndSave.ipynb. But the masks I reproduced are not consistent with the example you shown on the paper. 
For crl2800, you seem using the haibin's thin version instead of the ASCII file you provided. For inl1798 and inl2011, some faults are missing in the paper.
![image](https://user-images.githubusercontent.com/33403629/91709535-7a331f00-ebb5-11ea-83ca-8623ae8b214a.png)
![image](https://user-images.githubusercontent.com/33403629/91709683-ab135400-ebb5-11ea-9cc9-dc0996705d1d.png)
![image](https://user-images.githubusercontent.com/33403629/91709912-047b8300-ebb6-11ea-8312-c3453c10bc95.png)
the most obvious difference is the top area, faults in the paper extend to the very top row while the ASCII file not. 
For inl1796, the second left fault length is different compared to the left most fault, also for the rightmost two faults. For inl2011, ASCII file appeared to have more faults on the right side. 

I'm not sure why they are not consistent, could you help me confirm these questions? Appreciate your time and reply!

**Comment by augustoicaro** [comment]
Hello @anyuzoey. Thanks for your interest in my work, sorry for my late response. Tomorrow I will update the files that you requested and properly respond to your questions.

I had a few problems with the masks too. I will also check my notebooks about the masks and check your point about the lengths of the faults.

**Comment by augustoicaro** [comment]
Hello @anyuzoey,

You're right! The repository was outdated with older masks. I also implemented another image classification strategy to use border reflection to be able to classify all pixels. Then I edited each mask to extend the length of the fault, but in the end, I kept the first strategy of don't classify border pixels. This is why in the paper the faults' length is different.

I also update `ClassifyAndViewGSB` and `TrainAndSave` notebooks and add other two complementary notebooks related to metrics and feature maps to be aligned with the final version of my article.

About the shape of inline files, you are right. All slices were extracted with onpendTect from the GSB subvolume as I described in the article. I double-checked the opendTect slice exporter with null traces options as "pass" or "discard", but the result still the same. I don't know how to explain why this happens, I agree with you that the number of traces should be 500.

If this solves your question, please close the issue.

**Comment by anyuzoey** [comment]
Hi @augustoicaro 

Thank you for your explanation. Solved my issues.
